version: '3'
services:
  web_server:
    build: ./server
    container_name: web_server
    tty: true
    volumes:
      - .:/usr/src/app
    expose:
      - "5000"
    networks:
      - my_network

  client:
    build: ./client
    container_name: client
    tty: true
    volumes:
      - .:/usr/src/app
    networks:
      - my_network

networks:
  my_network:
